### ISSUE TITLE
Required script mbc not downloading

### ISSUE THREAD

**Issue by molnara** [mrchrisster/attract_mode#3]
Every time I run this script, it tries to download mbc from another repo and just hangs.

Then no error and it tries to load another game and if it's not an arcade game it just hangs.  Eventually when it gets to an arcade game it then works.

Can I just manually download the script?  I know it's not my connection as I just did an update_all and it worked fine.

**Comment by mrchrisster** [comment]
That's strange, since it uses the same logic as update-all script.
Can you try this version:
https://github.com/mrchrisster/attract_mode/releases/download/0.8/Attract_Mode.zip

**Comment by mrchrisster** [comment]
You can change
`mbcpath=/tmp/mbc` to `mbcpath=/media/fat/linux/mbc` if you don't want to download the tool every time. The tool can be downloaded here `https://github.com/mrchrisster/MiSTer_Batch_Control`
MBC is still in development since it has some bugs so at this point it's probably best to not make it permanent on your system

**Comment by mrchrisster** [comment]
Added offline instructions
